### ISSUE TITLE
Could you please update the tsv? thank you very much!

### ISSUE THREAD

**Issue by PubMedKG** [iit-Demokritos/drug_id_mapping#1]
Hi, your work is so nice, but the TSV data is not be updated for a long time. 

I am so sad that I am not good at java, so could you please update it?

Thank you very much much much!!!

**Comment by fotais** [comment]
> Hi, your work is so nice, but the TSV data is not be updated for a long time.
> 
> I am so sad that I am not good at java, so could you please update it?
> 
> Thank you very much much much!!!

Hello!
Thank you for your kind words.
The last update of the TSV file was approx. 1 year ago.
Since most databases used are not updated within a year period, we plan to update with the latest versions in the beginning of 2024.

**Comment by PubMedKG** [comment]
> > Hi, your work is so nice, but the TSV data is not be updated for a long time.
> > I am so sad that I am not good at java, so could you please update it?
> > Thank you very much much much!!!
> 
> Hello! Thank you for your kind words. The last update of the TSV file was approx. 1 year ago. Since most databases used are not updated within a year period, we plan to update with the latest versions in the beginning of 2024.

Oh, thank you so much!

**Comment by fotais** [comment]
The mapping file was updated based on the latest Drugbank Version 5.1.11

**Comment by PubMedKG** [comment]
> The mapping file was updated based on the latest Drugbank Version 5.1.11

Your work and you are so wonderful! Thank you so much much much again!!
